name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu_latest
    steps:
      - name: print greeting
        run: echo "Hello Vibhor"
      - name: print goodbye
        run: echo "Time to say goodbye"
    
